.TH marsadm 8 "January 20, 2015" "" "MARS Admin Tool"

.SH NAME
marsadm \- management of MARS resources

.SH SYNOPSIS
.B "marsadm \-h \-\-help"
.br
.B "marsadm \-v \-\-version "
.br
.br


.SH DESCRIPTION
MARS is a kernel-level asynchronous replication system for block devices.
It is tailored for long-distance replication and through network
bottlenecks.
By default, it works asynchronously (in contrast to DRBD).
.br
More infomation on concepts and differences to DRDB can be found at
https://github.com/schoebel/mars/blob/master/docu/MARS_LinuxTag2014.pdf?raw=true

.SH NOTICE
This manual page is only a placeholder.
Complete / authoritative documentation can be found in mars-manual.pdf
which should be also installed at your system.
.br
In addition, the newest version can be found at
https://github.com/schoebel/mars/blob/master/docu/mars-manual.pdf?raw=true

.br
A short summary of all available sub-commands and options can be
retrieved by invoking "marsadm --help".
